# Generated by Django 5.0.6 on 2024-06-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='edit_code',
            field=models.CharField(default='temp_default', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='security_code',
            field=models.CharField(default='temp_security_code', max_length=10),
            preserve_default=False,
        ),
    ]
